# Code is from Otago University COSC349 Lab9 'Using Vagrant to Deploy to EC2' 

#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|

    # Region for Amazon Educate.
    aws.region = "us-east-1"

    # Force synchronisation of files to the VM's
    override.nfs.functional = false
    override.vm.allowed_synced_folder_types = :rsync

    # Tells Amazon which public key to use.
    aws.keypair_name = "cosc349"
    # File location in the macOS account
    override.ssh.private_key_path = "~/.ssh/cosc349.pem"

    # Amazon EC2 instance type
    aws.instance_type = "t2.micro"

    # Security groups of VM
    aws.security_groups = ["sg-008ba1a2d3990485d", "sg-044301c01ad47855d"]

    # Availability_zone and subnet_id
    aws.availability_zone = "us-east-1a"
    aws.subnet_id = "subnet-53530034"
    
    # Virtual appliance used to create VM
    aws.ami = "ami-04763b3055de4860b"

    # Allows Vagrant to connect using username "ubuntu".
    override.ssh.username = "ubuntu"
  end

  # Install apache2 php php-mysql
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2 php libapache2-mod-php php-mysql
   
 # Change VM's webserver's configuration to use shared folder.
    cp /vagrant/test-website.conf /etc/apache2/sites-available/
    # install the configuration and disable the default
    a2ensite test-website
    a2dissite 000-default
    service apache2 reload

SHELL
end

